#!/bin/bash

cd /SERVICE

CONFIG_ARGS="s|CONFIG_PORT|${CONFIG_PORT}|g;\
        	s|CONFIG_PREFIX|${CONFIG_PREFIX}|g;\
        	s|CONFIG_DB_HOST|${CONFIG_DB_HOST}|g;\
        	s|CONFIG_DB_PORT|${CONFIG_DB_PORT}|g;\
        	s|CONFIG_DB_USER|${CONFIG_DB_USER}|g;\
        	s|CONFIG_DB_PASS|${CONFIG_DB_PASS}|g;\
        	s|CONFIG_DB_NAME|${CONFIG_DB_NAME}|g;\
        	s|CONFIG_ACCESS_TOKEN_SECRET|${CONFIG_ACCESS_TOKEN_SECRET}|g;\
        	s|CONFIG_REFRESH_TOKEN_SECRET|${CONFIG_REFRESH_TOKEN_SECRET}|g;\
        	s|CONFIG_REDIS_URL|${CONFIG_REDIS_URL}|g;\
        	s|CONFIG_REDIS_PORT|${CONFIG_REDIS_PORT}|g;\
        	s|CONFIG_REDIS_HOST|${CONFIG_REDIS_HOST}|g;\
        	s|CONFIG_REDIS_PASSWORD|${CONFIG_REDIS_PASSWORD}|g;\
        	s|CONFIG_REDIS_DB|${CONFIG_REDIS_DB}|g;\
			s|CONFIG_FRONTEND_URL|${CONFIG_FRONTEND_URL}|g"

sed -i -e "$CONFIG_ARGS" .env

yarn start

exec "$@"